### ISSUE TITLE
why老师发现了两个bug

### ISSUE THREAD

**Issue by CoderTanX** [coderwhy/DouYuZB#1]
1、顶部的titleLabel如果重复点击，颜色会有问题
2、如果快速滑动中间的collectview到最后，最后一个titleLabel的颜色有问题

非常感谢老师无私分享的视频

**Comment by coderwhy** [comment]
谢谢哈
第一个Bug已经修复了，我当时忘记做一个判断了，后面视频中我会讲到。
第二个Bug目前没有测试出来，测试出来我会及时修复。
很细心👍

**Comment by CoderTanX** [comment]
第二个问题这样测：中间的collectionView（pagecontentview）不是有四个控制器嘛，从第二个控制器向左连续快速滑动到第四个控制器（只有连续快速滑动才会出现），会发现第四个titleLabel的textcolor是灰色的，本应该是橘色的。

**Comment by dvxiaofan** [comment]
老师接下来会用 Xcode8并结合 Swift3讲课吗?

**Comment by zhao95** [comment]
来到,点赞~~~

**Comment by ptlCoder** [comment]
讲得非常好  受益匪浅  谢谢老师的无私奉献 👍

**Comment by ichenwanbing** [comment]
第一个bug只需要把改变颜色的顺序变一下就好了

**Comment by ac1217** [comment]
第二个Bug是滑动到最后一个快速滑多一下会闪一下，这样操作会导致最后回调时progress会变一下0，所以先变一下灰色，再变黄色，我这边直接用progress做判断就没问题了

if progress == 0 {
                progress = 1
                targetIndex = sourceIndex
 }

**Comment by dvxiaofan** [comment]
今天刚操作到这里, 第一个bug 我是在点击 titlelabel 时做了一个判断,  如果是重复点击, 则不进行切换操作,  就没问题了.
