### ISSUE TITLE
老师接下来会用 Xcode8 并结合 Swift3 讲课吗?

### ISSUE THREAD

**Issue by dvxiaofan** [coderwhy/DouYuZB#2]
老师接下来会用 Xcode8 并结合 Swift3 讲课吗?

**Comment by coderwhy** [comment]
嗯嗯, 后面会用Swift3.0来讲

**Comment by ichenwanbing** [comment]
什么时候啊，现在更新Xcode项目运行不了

**Comment by dvxiaofan** [comment]
建议你直接用 Xcode8 和 Swift3.0 来学习操作.  把老师用的语法和 API 改成 Swift3.0 的.  我现在就是这样.  因为转换老师原有代码有点麻烦. 自己适配最新的就 OK 了.
