### ISSUE TITLE
codewhy老师，用xcode8转为swift2.3的代码Alamofire一直报错怎么解决？

### ISSUE THREAD

**Issue by LiuXingCode** [coderwhy/DouYuZB#3]
如标题，怎么解决？

**Comment by ac1217** [comment]
我直接用支持swift3.0的alamofire，最新版的，不过只支持ios9+

**Comment by coderwhy** [comment]
嗯, swift3.0的alamofire只支持9.0+
后面我会用Xcode8.0来讲的

**Comment by coderwhy** [comment]
已经适配了Xcode8.0&Swift3.0,请查看最新的视频
