### ISSUE TITLE
项目用Xcode8打开swift3.0环境就用不了了  why老师指导一下

### ISSUE THREAD

**Issue by ichenwanbing** [coderwhy/DouYuZB#4]
项目用Xcode8打开swift3.0环境就用不了了  why老师指导一下

**Comment by dvxiaofan** [comment]
自己直接在 Xcode8 上用 Swift3.0 去写.  可以运行.  我觉得改老师的代码太麻烦,  还不如自己从一开始就用最新的语法去写. 能实现效果就好

**Comment by coderwhy** [comment]
可以适配的, 最近在录swift3.0语法视频
后面更新斗鱼我就会适配哈.

**Comment by ichenwanbing** [comment]
老师辛苦

发自网易邮箱大师
在2016年09月26日 22:02，coderwhy 写道:

可以适配的, 最近在录swift3.0语法视频
后面更新斗鱼我就会适配哈.

**Comment by coderwhy** [comment]
已经适配了Xcode8.0&Swift3.0,请查看最新的视频.
